# **FINELITE** (AI-powered credit card limit prediction ) **Machine Learning**
* This code builds a Regression Machine Learning project to predict a customer's Credit Limit using customer-related financial and demographic information.

**Import Required Libraries**

In [1]:
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt

C:\Users\Asus\AppData\Roaming\Python\Python313\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

**Load the Excel Dataset**

In [2]:
df = pd.read_excel("../Datasets/Credir_Card_Bank.xlsx")

In [3]:
pd.set_option("display.max_columns",None)
df

,Customer_ID,Age,Gender,Employment_Type,Occupation,Monthly_Income,Annual_Income,Credit_Score,Years_With_Bank,Existing_Credit_Cards,Existing_Credit_Limit,Loan_Count,EMI_Per_Month,Debt_To_Income_Ratio,Savings_Balance,Investment_Value,Avg_Monthly_Transactions,Avg_Monthly_Spending,Credit_Utilization,Credit_History_Years,Missed_Payments,Late_Payment_Count,Number_of_Defaults,Residential_Status,PAN_Verified,KYC_Status,Fraud_Flag,Credit_Limit
0,CUST00001,41,Female,Salaried,Sales Executive,140273,1683276,811,4,4,706088,3,49141,0.33,221285,248294,221,69992.0,34,11,0,8,0,Rent,Yes,Complete,No,1373925
1,CUST00002,23,Male,Self-Employed,Business Owner,209521,2514252,837,12,2,527133,1,13338,0.24,348033,1197179,199,17170.0,71,20,3,3,0,Own,Yes,Complete,No,1902449
2,CUST00003,45,Female,Salaried,Designer,47682,572184,679,2,6,281776,1,3618,0.18,603413,1459090,76,16871.0,88,12,5,2,0,Rent,Yes,Complete,No,1165913
3,CUST00004,39,Male,Salaried,Doctor,214966,2579592,660,5,0,656977,0,16114,0.05,1113302,1362180,112,193469.4,66,4,3,5,0,Rent,Yes,Complete,No,1869491
4,CUST00005,58,Male,Self-Employed,Designer,30051,360612,589,18,0,267892,4,36361,0.32,824809,595409,46,6024.0,70,1,4,2,0,Own,Yes,Complete,No,825275
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,CUST04996,48,Male,Salaried,Doctor,55078,660936,824,12,1,806871,4,34469,0.10,433388,77558,211,30151.0,91,7,4,4,0,Rent,Yes,Complete,No,1156917
4996,CUST04997,59,Female,Self-Employed,Accountant,107040,1284480,840,0,1,896965,4,40182,0.25,254850,1934214,61,86594.0,28,22,1,6,0,Own,Yes,Complete,No,1458578
4997,CUST04998,26,Female,Salaried,Doctor,168754,2025048,632,19,0,712921,1,52001,0.09,91677,868069,210,42256.0,38,11,3,1,0,Rent,Yes,Complete,No,1342610
4998,CUST04999,42,Male,Salaried,Manager,197110,2365320,734,9,2,91279,1,40678,0.13,1256605,1989152,49,177399.0,15,3,2,2,0,Own,Yes,Complete,No,1868828
4999,CUST05000,55,Female,Self-Employed,Business Owner,126915,1522980,709,12,5,988815,2,26647,0.33,3578,743083,187,29010.0,49,19,3,2,0,Own,Yes,Complete,No,1272502

**Check Missing Values**

In [4]:
df.isnull().sum()

Customer_ID                 0
Age                         0
Gender                      0
Employment_Type             0
Occupation                  0
Monthly_Income              0
Annual_Income               0
Credit_Score                0
Years_With_Bank             0
Existing_Credit_Cards       0
Existing_Credit_Limit       0
Loan_Count                  0
EMI_Per_Month               0
Debt_To_Income_Ratio        0
Savings_Balance             0
Investment_Value            0
Avg_Monthly_Transactions    0
Avg_Monthly_Spending        0
Credit_Utilization          0
Credit_History_Years        0
Missed_Payments             0
Late_Payment_Count          0
Number_of_Defaults          0
Residential_Status          0
PAN_Verified                0
KYC_Status                  0
Fraud_Flag                  0
Credit_Limit                0
dtype: int64

**Check Data Types**

In [5]:
df.dtypes

Customer_ID                     str
Age                           int64
Gender                          str
Employment_Type                 str
Occupation                      str
Monthly_Income                int64
Annual_Income                 int64
Credit_Score                  int64
Years_With_Bank               int64
Existing_Credit_Cards         int64
Existing_Credit_Limit         int64
Loan_Count                    int64
EMI_Per_Month                 int64
Debt_To_Income_Ratio        float64
Savings_Balance               int64
Investment_Value              int64
Avg_Monthly_Transactions      int64
Avg_Monthly_Spending        float64
Credit_Utilization            int64
Credit_History_Years          int64
Missed_Payments               int64
Late_Payment_Count            int64
Number_of_Defaults            int64
Residential_Status              str
PAN_Verified                    str
KYC_Status                      str
Fraud_Flag                      str
Credit_Limit                  int64
dtype: object

**Remove Unnecessary Columns**

In [6]:
df = df.drop(columns=["Customer_ID","Monthly_Income","PAN_Verified", "KYC_Status"])

**Convert Categorical Columns into Numerical Columns**

In [7]:
df=pd.get_dummies(df,columns=['Gender','Employment_Type','Occupation','Residential_Status','Fraud_Flag'],drop_first=True)

**Correlation Analysis**

In [8]:
df.corr(numeric_only=True)

,Age,Annual_Income,Credit_Score,Years_With_Bank,Existing_Credit_Cards,Existing_Credit_Limit,Loan_Count,EMI_Per_Month,Debt_To_Income_Ratio,Savings_Balance,Investment_Value,Avg_Monthly_Transactions,Avg_Monthly_Spending,Credit_Utilization,Credit_History_Years,Missed_Payments,Late_Payment_Count,Number_of_Defaults,Credit_Limit,Gender_Male,Employment_Type_Self-Employed,Occupation_Business Owner,Occupation_Designer,Occupation_Doctor,Occupation_Manager,Occupation_Sales Executive,Occupation_Software Engineer,Occupation_Teacher,Residential_Status_Rent,Fraud_Flag_Yes
Age,1.000000,0.000586,-0.004417,0.001938,0.033044,0.015468,0.013240,0.018521,-0.001949,-0.005467,0.004425,-0.001134,-0.001287,-0.003089,-0.008412,-0.005983,0.040799,-0.004269,-0.003773,0.002319,-0.008282,0.019498,-0.013729,-0.023112,-0.013378,0.009453,0.018038,0.010175,0.015796,0.011968
Annual_Income,0.000586,1.000000,-0.014696,-0.022105,-0.009906,0.012751,-0.021474,0.008250,0.001379,-0.005543,-0.022537,0.006890,0.628810,0.009198,0.015196,-0.015982,0.010823,0.021510,0.845154,-0.019894,-0.013964,-0.005210,-0.030928,-0.001082,0.005133,0.020190,-0.006411,0.014141,-0.000174,0.012096
Credit_Score,-0.004417,-0.014696,1.000000,0.019403,-0.004087,0.013865,0.000986,0.007697,0.003660,-0.017790,0.008831,0.007820,-0.024062,0.010176,0.015656,0.012040,0.005148,-0.356127,0.381760,-0.005280,0.018220,-0.008083,-0.000801,-0.009627,0.007800,-0.000494,0.004224,0.006600,0.013482,-0.001105
Years_With_Bank,0.001938,-0.022105,0.019403,1.000000,-0.002723,-0.002130,0.015532,-0.028507,0.003181,-0.008334,0.024473,0.009605,-0.009075,-0.014714,-0.015606,-0.015810,0.013017,0.000524,-0.006032,-0.024309,0.009853,0.007863,-0.021635,0.000628,0.020218,0.007605,-0.027541,0.018810,-0.001477,-0.018259
Existing_Credit_Cards,0.033044,-0.009906,-0.004087,-0.002723,1.000000,0.033060,-0.003890,0.003283,-0.003248,-0.001928,-0.016971,-0.013516,-0.016883,-0.006137,-0.004833,-0.014084,-0.023603,0.001017,-0.013278,-0.009285,-0.022204,-0.007730,0.015919,0.009828,0.019894,-0.016028,-0.000698,-0.000061,-0.004925,0.008651
Existing_Credit_Limit,0.015468,0.012751,0.013865,-0.002130,0.033060,1.000000,0.034080,-0.017020,0.002645,0.000433,0.009725,0.009526,-0.023652,0.036823,-0.019915,-0.020550,0.017083,-0.000667,0.019990,-0.019820,0.003818,0.009030,-0.020939,0.018977,-0.010979,0.002246,-0.032448,0.009569,0.016641,0.004880
Loan_Count,0.013240,-0.021474,0.000986,0.015532,-0.003890,0.034080,1.000000,-0.020558,0.002716,-0.018963,-0.011324,-0.001872,-0.023220,-0.016886,-0.010709,-0.021134,-0.013663,0.002175,-0.021052,0.005230,-0.002643,0.000779,0.007689,-0.000040,-0.025225,0.021731,0.014784,-0.034415,0.001218,-0.011943
EMI_Per_Month,0.018521,0.008250,0.007697,-0.028507,0.003283,-0.017020,-0.020558,1.000000,0.016604,0.023609,-0.010898,0.009866,0.006183,-0.022559,0.009839,-0.003114,-0.014387,-0.013755,-0.156737,0.020868,0.008767,-0.006668,0.011595,0.024559,-0.016146,-0.031016,0.007295,0.011640,0.008310,-0.020635
Debt_To_Income_Ratio,-0.001949,0.001379,0.003660,0.003181,-0.003248,0.002645,0.002716,0.016604,1.000000,-0.014972,-0.015340,-0.013335,-0.016694,-0.013320,0.003050,0.004718,0.007727,-0.012275,-0.108885,-0.000813,0.000062,-0.006106,0.007094,-0.002632,-0.005053,-0.003890,0.013122,-0.003303,-0.014926,0.020259
Savings_Balance,-0.005467,-0.005543,-0.017790,-0.008334,-0.001928,0.000433,-0.018963,0.023609,-0.014972,1.000000,-0.009769,-0.035111,0.009153,0.031341,-0.001835,-0.005678,0.004422,0.007451,0.199066,0.018269,-0.025415,0.025395,-0.005909,-0.008495,0.005105,-0.008079,0.016659,-0.004425,0.016218,-0.024266
Investment_Value,0.004425,-0.022537,0.008831,0.024473,-0.016971,0.009725,-0.011324,-0.010898,-0.015340,-0.009769,1.000000,-0.001998,-0.022592,-0.001282,0.016616,-0.023002,0.003378,0.002820,0.135956,0.013065,0.003381,-0.016101,-0.002854,-0.001575,-0.000027,0.015892,0.013265,-0.012010,0.001130,-0.008183
Avg_Monthly_Transactions,-0.001134,0.006890,0.007820,0.009605,-0.013516,0.009526,-0.001872,0.009866,-0.013335,-0.035111,-0.001998,1.000000,0.002787,-0.017698,0.006698,-0.007103,0.022330,-0.014624,0.002812,0.004414,0.000540,-0.010116,0.003275,0.001473,-0.000838,-0.003135,-0.004612,0.008297,0.008103,0.009149
Avg_Monthly_Spending,-0.001287,0.628810,-0.024062,-0.009075,-0.016883,-0.023652,-0.023220,0.006183,-0.016694,0.009153,-0.022592,0.002787,1.000000,0.026232,0.029087,-0.004546,0.009740,0.029569,0.526918,-0.015160,-0.001424,-0.007941,-0.000805,-0.003430,-0.017023,0.001031,-0.000786,0.014060,0.011694,0.015298
Credit_Utilization,-0.003089,0.009198,0.010176,-0.014714,-0.006137,0.036823,-0.016886,-0.022559,-0.013320,0.031341,-0.001282,-0.017698,0.026232,1.000000,-0.000261,0.014654,-0.004649,0.007232,0.022004,-0.009104,-0.003647,0.006344,-0.009415,-0.026341,0.010059,0.009745,0.006878,0.006935,0.021678,0.009965
Credit_History_Years,-0.008412,0.015196,0.015656,-0.015606,-0.004833,-0.019915,-0.010709,0.009839,0.003050,-0.001835,0.016616,0.006698,0.029087,-0.000261,1.000000,0.009719,0.001906,-0.017061,0.021278,0.019029,0.023500,-0.005756,0.003240,0.001366,-0.002869,0.006437,0.016349,-0.021836,-0.000555,-0.003999
Missed_Payments,-0.005983,-0.015982,0.012040,-0.015810,-0.014084,-0.020550,-0.021134,-0.003114,0.004718,-0.005678,-0.023002,-0.007103,-0.004546,0.014654,0.009719,1.000000,-0.011781,-0.016866,-0.011587,0.010577,-0.016046,0.010300,0.007655,-0.012723,-0.002325,0.012123,-0.010411,0.002908,-0.009442,0.001244
Late_Payment_Count,0.040799,0.010823,0.005148,0.013017,-0.023603,0.017083,-0.013663,-0.014387,0.007727,0.004422,0.003378,0.022330,0.009740,-0.004649,0.001906,-0.011781,1.000000,-0.023218,0.017900,-0.004393,0.023430,-0.002196,0.009810,-0.010258,0.008475,0.027971,-0.034094,0.006554,0.013211,-0.014455
Number_of_Defaults,-0.004269,0.021510,-0.356127,0.000524,0.001017,-0.000667,0.002175,-0.013755,-0.012275,0.007451,0.002820,-0.014624,0.029569,0.007232,-0.017061,-0.016866,-0.023218,1.000000,-0.258251,-0.016525,-0.010673,-0.001595,0.003565,0.009045,0.004495,-0.003287,0.007788,-0.015516,0.004021,0.001689
Credit_Limit,-0.003773,0.845154,0.381760,-0.006032,-0.013278,0.019990,-0.021052,-0.156737,-0.108885,0.199066,0.135956,0.002812,0.526918,0.022004,0.021278,-0.011587,0.017900,-0.258251,1.000000,-0.013811,-0.010524,-0.002183,-0.031860,-0.011644,0.010727,0.024079,-0.002353,0.012500,0.007614,0.004684
Gender_Male,0.002319,-0.019894,-0.005280,-0.024309,-0.009285,-0.019820,0.005230,0.020868,-0.000813,0.018269,0.013065,0.004414,-0.015160,-0.009104,0.019029,0.010577,-0.004393,-0.016525,-0.013811,1.000000,0.003257,0.009443,-0.019774,-0.031361,-0.005992,-0.014237,0.018237,0.018036,-0.015654,-0.020586
Employment_Type_Self-Employed,-0.008282,-0.013964,0.018220,0.009853,-0.022204,0.003818,-0.002643,0.008767,0.000062,-0.025415,0.003381,0.000540,-0.001424,-0.003647,0.023500,-0.016046,0.023430,-0.010673,-0.010524,0.003257,1.000000,0.022791,-0.020900,-0.024901,-0.001745,-0.001326,0.014706,-0.002359,0.014039,-0.000603
Occupation_Business Owner,0.019498,-0.005210,-0.008083,0.007863,-0.007730,0.009030,0.000779,-0.006668,-0.006106,0.025395,-0.016101,-0.010116,-0.007941,0.006344,-0.005756,0.010300,-0.002196,-0.001595,-0.002183,0.009443,0.022791,1.000000,-0.139330,-0.135116,-0.132858,-0.140926,-0.139822,-0.132732,0.013454,-0.007062
Occupation_Designer,-0.013729,-0.030928,-0.000801,-0.021635,0.015919,-0.020939,0.007689,0.011595,0.007094,-0.005909,-0.002854,0.003275,-0.000805,-0.009415,0.003240,0.007655,0.009810,0.003565,-0.031860,-0.019774,-0.020900,-0.139330,1.000000,-0.145162,-0.142736,-0.151403,-0.150218,-0.142601,0.008859,0.027180
Occupation_Doctor,-0.023112,-0.001082,-0.009627,0.000628,0.009828,0.018977,-0.000040,0.024559,-0.002632,-0.008495,-0.001575,0.001473,-0.003430,-0.026341,0.001366,-0.012723,-0.010258,0.009045,-0.011644,-0.031361,-0.024901,-0.135116,-0.145162,1.000000,-0.138419,-0.146824,-0.145674,-0.138287,0.007724,-0.002797
Occupation_Manager,-0.013378,0.005133,0.007800,0.020218,0.019894,-0.010979,-0.025225,-0.016146,-0.005053,0.005105,-0.000027,-0.000838,-0.017023,0.010059,-0.002869,-0.002325,0.008475,0.004495,0.010727,-0.005992,-0.001745,-0.132858,-0.142736,-0.138419,1.000000,-0.144370,-0.143240,-0.135976,0.012684,0.024590
Occupation_Sales Executive,0.009453,0.020190,-0.000494,0.007605,-0.016028,0.002246,0.021731,-0.031016,-0.003890,-0.008079,0.015892,-0.003135,0.001031,0.009745,0.006437,0.012123,0.027971,-0.003287,0.024079,-0.014237,-0.001326,-0.140926,-0.151403,-0.146824,-0.144370,1.000000,-0.151938,-0.144233,0.001169,-0.011631
Occupation_Software Engineer,0.018038,-0.006411,0.004224,-0.027541,-0.000698,-0.032448,0.014784,0.007295,0.013122,0.016659,0.013265,-0.004612,-0.000786,0.006878,0.016349,-0.010411,-0.034094,0.007788,-0.002353,0.018237,0.014706,-0.139822,-0.150218,-0.145674,-0.143240,-0.151938,1.000000,-0.143104,-0.023160,-0.017543
Occupation_Teacher,0.010175,0.014141,0.006600,0.018810,-0.000061,0.009569,-0.034415,0.011640,-0.003303,-0.004425,-0.012010,0.008297,0.014060,0.006935,-0.021836,0.002908,0.006554,-0.015516,0.012500,0.018036,-0.002359,-0.132732,-0.142601,-0.138287,-0.135976,-0.144233,-0.143104,1.000000,-0.011348,-0.008331
Residential_Status_Rent,0.015796,-0.000174,0.013482,-0.001477,-0.004925,0.016641,0.001218,0.008310,-0.014926,0.016218,0.001130,0.008103,0.011694,0.021678,-0.000555,-0.009442,0.013211,0.004021,0.007614,-0.015654,0.014039,0.013454,0.008859,0.007724,0.012684,0.001169,-0.023160,-0.011348,1.000000,0.013414
Fraud_Flag_Yes,0.011968,0.012096,-0.001105,-0.018259,0.008651,0.004880,-0.011943,-0.020635,0.020259,-0.024266,-0.008183,0.009149,0.015298,0.009965,-0.003999,0.001244,-0.014455,0.001689,0.004684,-0.020586,-0.000603,-0.007062,0.027180,-0.002797,0.024590,-0.011631,-0.017543,-0.008331,0.013414,1.000000

**Separate Features and Target Variable**

In [9]:
x=df.drop(['Credit_Limit'],axis=1).values
y=df['Credit_Limit'].values

**Split Data into Training and Testing Sets**

In [10]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest= train_test_split(x,y,test_size=0.2)

# **Linear Regression**

In [11]:
from sklearn.linear_model import LinearRegression
modellinear= LinearRegression()
modellinear.fit(xtrain,ytrain)
yplinear= modellinear.predict(xtest)

In [12]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
r2linear = r2_score(ytest,yplinear)
r2linear * 100

96.47130479242297

In [13]:
MAE = mean_absolute_error(ytest, yplinear)
print(MAE)
MSE= mean_squared_error(ytest, yplinear)
print(MSE)
RMSE=np.sqrt(mean_squared_error(ytest, yplinear))
print(RMSE)

39341.89602730012
3005084204.9317107
54818.64833185611

**15-Fold Cross-Validation for Linear Regression**

In [14]:
from sklearn.model_selection import cross_val_score
modelcvlinear = LinearRegression()
sc = cross_val_score(modelcvlinear,x,y,cv=15,scoring='r2')
print(sc)
sc.mean()

[0.97380453 0.97450757 0.96508225 0.96634298 0.96871965 0.96858634
 0.96928801 0.96014124 0.96315232 0.95923073 0.96499081 0.9665015
 0.96770515 0.96049703 0.96706826]

np.float64(0.9663745582830736)

# **Decision Tree Regression**

In [15]:
from sklearn.tree import DecisionTreeRegressor
modeldr = DecisionTreeRegressor()
modeldr.fit(xtrain,ytrain)
ypdr=modeldr.predict(xtest)

In [16]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
r2dr = r2_score(ytest,ypdr)
print("R2 score of decision tree is",r2dr * 100)
MAE1 = mean_absolute_error(ytest, ypdr)
print("Mean absolute error for decision tree",MAE1)
MSE1= mean_squared_error(ytest, ypdr)
print("Mean squared error for decision tree",MSE1)
RMSE1=np.sqrt(mean_squared_error(ytest, ypdr))
print("Root mean squared error for decision tree",RMSE1)

R2 score of decision tree is 90.32258516356731
Mean absolute error for decision tree 71990.539
Mean squared error for decision tree 8241416375.971
Root mean squared error for decision tree 90782.24703085399

**15-Fold Cross-Validation for Decision Tree**

In [17]:
from sklearn.model_selection import cross_val_score
modelcvdr = DecisionTreeRegressor()
sc1 = cross_val_score(modelcvdr,x,y,cv=15,scoring='r2')
print(sc1)
sc1.mean()

[0.92512229 0.92467659 0.9199848  0.92406861 0.92401939 0.91074061
 0.92888959 0.91368112 0.90679182 0.92314953 0.91798501 0.91919577
 0.91836065 0.91451425 0.9213074 ]

np.float64(0.9194991605693044)

**Hyperparameter Tuning — Decision Tree**

In [18]:
from sklearn.model_selection import GridSearchCV 
from sklearn.tree import DecisionTreeRegressor 
tunned_parameters = { 'criterion': ['squared_error', 'friedman_mse', 'absolute_error'], 
                      'max_depth': [3, 5, 10, 15, 20, None], 
                      'min_samples_split': [2, 5, 10], 
                      'min_samples_leaf': [1, 2, 4] }
model_gscv = DecisionTreeRegressor(random_state=42)
new_model = GridSearchCV( estimator=model_gscv, param_grid=tunned_parameters, scoring='r2', cv=5 )
new_model.fit(xtrain, ytrain) 
print("Best Parameters:",new_model.best_params_) 
print("\nBest R2 Score:",new_model.best_score_)

Best Parameters: {'criterion': 'squared_error', 'max_depth': 15, 'min_samples_leaf': 4, 'min_samples_split': 10}

Best R2 Score: 0.9220001658366698

C:\Users\Asus\AppData\Roaming\Python\Python313\site-packages\sklearn\model_selection\_validation.py:489: FitFailedWarning:
270 fits failed out of a total of 810.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
270 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Asus\AppData\Roaming\Python\Python313\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\AppData\Roaming\Python\Python313\site-packages\sklearn\base.py", line 1393, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Asus\AppData\Roaming\Python\Python313\site-packages\sklearn\base.py", line 554, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Asus\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'squared_error', 'poisson', 'absolute_error'}. Got 'friedman_mse' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\Asus\AppData\Roaming\Python\Python313\site-packages\sklearn\model_selection\_search.py:1234: UserWarning: One or more of the test scores are non-finite: [0.77866548 0.77866548 0.77866548 0.77866548 0.77866548 0.77866548
 0.77866548 0.77866548 0.77866548 0.8682845  0.8682845  0.8682845
 0.8682845  0.8682845  0.8682845  0.8682845  0.8682845  0.8682845
 0.91365983 0.91383464 0.91688647 0.91522735 0.91686373 0.91835408
 0.91980324 0.91980324 0.92072917 0.9096162  0.91133555 0.91638393
 0.91320863 0.91412258 0.9181657  0.9209243  0.9209243  0.92200017
 0.90950204 0.91270873 0.91635156 0.91458527 0.91394904 0.91823413
 0.9209243  0.9209243  0.92200017 0.90985385 0.91270873 0.91635156
 0.91458527 0.91394904 0.91823413 0.9209243  0.9209243  0.92200017
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.77664237 0.77664237 0.77664237 0.77664237 0.77664237 0.77664237
 0.77664237 0.77664237 0.77664237 0.86363598 0.86363598 0.86363598
 0.86363598 0.86363598 0.86363598 0.86379344 0.86379344 0.86379344
 0.90640528 0.90600922 0.90879981 0.90987789 0.910113   0.91158998
 0.91230898 0.91230898 0.91295224 0.90034972 0.9022985  0.90695873
 0.90887681 0.90882364 0.91175407 0.91401586 0.91401586 0.91428859
 0.89890222 0.90168601 0.90709366 0.90878292 0.90978085 0.91158336
 0.9141307  0.9141307  0.9142591  0.89891973 0.90198837 0.90732449
 0.90878292 0.90978085 0.91158336 0.9141307  0.9141307  0.9142591 ]
  warnings.warn(

# **Random Forest Regression**

In [19]:
from sklearn.ensemble import RandomForestRegressor 
modelrf = RandomForestRegressor( random_state=42 ) 
modelrf.fit(xtrain, ytrain) 
yprf = modelrf.predict(xtest)

In [20]:
r2rf = r2_score(ytest, yprf) 
print( "R2 score of random forest is", r2rf * 100 ) 
MAE2 = mean_absolute_error( ytest, yprf )
print( "Mean absolute error for random forest", MAE2 )
MSE2 = mean_squared_error( ytest, yprf ) 
print( "Mean squared error for random forest", MSE2)
RMSE2 = np.sqrt(MSE2) 
print( "Root mean squared error for random forest", RMSE2)

R2 score of random forest is 97.11062425988783
Mean absolute error for random forest 39478.12547
Mean squared error for random forest 2460631164.7658668
Root mean squared error for random forest 49604.74941742844

**Cross-Validation — Random Forest**

In [21]:
from sklearn.model_selection import cross_val_score
modelcvrf = RandomForestRegressor()
sc2 = cross_val_score(modelcvrf,x,y,cv=15,scoring='r2')
print(sc2)
sc2.mean()

[0.97866371 0.97632816 0.97351044 0.97729358 0.97641027 0.97441588
 0.97772159 0.97386373 0.97527815 0.97331198 0.97490917 0.9738275
 0.9744064  0.97105762 0.96908527]

np.float64(0.9746722317584745)

**Random Forest Hyperparameter Tuning**

In [22]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
tunned_parameters_rf = {'n_estimators': [100, 200],
                        'max_depth': [10, None],
                        'min_samples_split': [2, 5],
                        'min_samples_leaf': [1, 2]}
model_gscv_rf = RandomForestRegressor(random_state=42,n_jobs=-1)
new_model_rf = GridSearchCV(estimator=model_gscv_rf,param_grid=tunned_parameters_rf,scoring='r2',cv=5,n_jobs=-1)
new_model_rf.fit(xtrain, ytrain)
print("Best Parameters:", new_model_rf.best_params_)
print("\nBest R2 Score:", new_model_rf.best_score_)

Best Parameters: {'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 200}

Best R2 Score: 0.9709199315587504

# **XGBoost Regression**

In [23]:
from xgboost import XGBRegressor
modelxgbr = XGBRegressor( random_state=42 ) 
modelxgbr.fit(xtrain, ytrain) 
ypxgbr = modelxgbr.predict(xtest)

In [24]:
r2xgbr = r2_score(ytest, ypxgbr) 
print( "R2 score of XGBoost is", r2xgbr * 100 ) 
MAE3 = mean_absolute_error( ytest, ypxgbr)
print( "Mean absolute error for XGBoost", MAE3 )
MSE3 = mean_squared_error( ytest, ypxgbr) 
print( "Mean squared error for XGBoost", MSE3)
RMSE3 = np.sqrt(MSE3) 
print( "Root mean squared error for XGBoost", RMSE3)

R2 score of XGBoost is 98.5798716545105
Mean absolute error for XGBoost 27771.841796875
Mean squared error for XGBoost 1209400832.0
Root mean squared error for XGBoost 34776.44076095195

**15-Fold Cross-Validation — XGBoost**

In [25]:
from sklearn.model_selection import cross_val_score
modelcvxgbr = XGBRegressor()
sc3 = cross_val_score(modelcvxgbr,x,y,cv=15,scoring='r2')
print(sc3)
sc3.mean()

[0.98880887 0.98983073 0.9887017  0.98991847 0.98802769 0.98874599
 0.98821008 0.98885518 0.98975903 0.98574919 0.98909217 0.98831278
 0.98873585 0.98917454 0.98640716]

np.float64(0.9885552962621053)

**XGBoost Hyperparameter Tuning**

In [26]:
from sklearn.model_selection import GridSearchCV
from xgboost import XGBRegressor
tunned_parameters_xgb = {'n_estimators': [100, 200],
                         'learning_rate': [0.05, 0.1],
                         'max_depth': [3, 5],
                         'subsample': [0.8, 1.0],
                         'colsample_bytree': [0.8, 1.0]}
model_gscv_xgb = XGBRegressor(objective='reg:squarederror',random_state=42,n_jobs=-1)
new_model_xgb = GridSearchCV(estimator=model_gscv_xgb,param_grid=tunned_parameters_xgb,scoring='r2',cv=5,n_jobs=-1)
new_model_xgb.fit(xtrain, ytrain)
print("Best Parameters:", new_model_xgb.best_params_)
print("\nBest R2 Score:", new_model_xgb.best_score_)

Best Parameters: {'colsample_bytree': 1.0, 'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 200, 'subsample': 0.8}

Best R2 Score: 0.9956006169319153